kind: RabbitmqCluster
apiVersion: rabbitmq.com/v1beta1
metadata:
  name: rabbitmq
  namespace: meu-primeiro-cluster-rabbitmq
spec:
  replicas: 2
  image: rabbitmq:3.9.18-management
  service:
    type: ClusterIP
  resources:
    requests:
      cpu: 1
      memory: 1Gi
    limits:
      cpu: 1
      memory: 1Gi
EOF
